name: Albert Iosevka Custom Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发该工作流

jobs:
  build:
    name: Build ${{ matrix.fontName }} font
    if: github.repository == 'ylagr/Iosevka'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fontName: ["IosevkaYlagr"]

    steps:
      # Checkout repository into `iosevka` sub directory
      - uses: actions/checkout@v4
        with:
          path: iosevka

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install ttfautohint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font ${{ matrix.fontName }}
        shell: bash
        working-directory: iosevka
        run: |
          npm install
          npm run build -- contents::${{ matrix.fontName }}

      - name: Set tag name env
        run: |
          echo "NOW=v$(TZ='Asia/Shanghai' date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Publish Release
        id: publish_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NOW }}
          draft: false
          prerelease: false
          body: >
            针对原版`Iosevka`字体过于瘦高进行了下面的优化：

            1. `Iosevka`字体参考`FiraCode`风格，调整了i、r、l、t和1、4、0等数字的样式。

            2. 加宽了`Iosevka`字体，宽度从默认的`500`增加到`520`，中文相应的从`1000`增加到`1040`，保持等宽。

            3. `Iosevka`字体编译时使能`TXTR`特性，即Monaspace字体的`text healing`。

            4. 中文字体是[霞鹜文楷Lite等宽](${{ env.LXGW_WENKAI_LITE }})。

            5. FiraCode风格中英文合并字体是[${{ env.SS05_ID }}-Regular.ttf](${{ github.server_url }}/${{ github.repository }}/releases/download/${{ env.NOW }}/${{ env.SS05_ID }}-Regular.ttf)。

            6. Pragma风格的中英文合并字体是[${{ env.PRAGMA_ID }}-Regular.ttf](${{ github.server_url }}/${{ github.repository }}/releases/download/${{ env.NOW }}/${{ env.PRAGMA_ID }}-Regular.ttf)。

            ![IosevkaTermSS05NFM+LXGWWenKaiMonoLite-Regular-demo](https://github.com/georgealbert/MyNerdFonts/blob/main/screenshots/IosevkaTermSS05NFM%2BLXGWWenKaiMonoLite-Regular-demo.png)
            Iosevka原版和改版对比：
            ![Iosevka_diff](https://github.com/georgealbert/MyNerdFonts/blob/main/screenshots/character.png)

            ${{ env.release_body }}


            Built with
            [Github Workflow #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          files: |
            iosevka/dist/${{ env.SS05 }}/TTF/${{ env.SS05 }}-Regular.ttf
            iosevka/dist/${{ env.SS05 }}/TTF/${{ env.SS05 }}-Italic.ttf
            iosevka/dist/${{ env.PRAGMA }}/TTF/${{ env.PRAGMA }}-Regular.ttf
            iosevka/dist/${{ env.PRAGMA }}/TTF/${{ env.PRAGMA }}-Italic.ttf
            ${{ env.SS05 }}NerdFontMono-Regular.ttf
            ${{ env.SS05 }}NerdFontMono-Italic.ttf
            ${{ env.PRAGMA }}NerdFontMono-Regular.ttf
            ${{ env.PRAGMA }}NerdFontMono-Italic.ttf
            ${{ env.SS05_ID }}-Regular.ttf
            ${{ env.PRAGMA_ID }}-Regular.ttf
